### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by Den4yk** [Neamiades/CoinsDiffusion#7]
Sort fields by modifiers in next files:
https://github.com/Neamiades/CoinsDiffusion/blob/90c1fe39fb8ce5285ed7144c0c35efc09d306243/CoinsDiffusion/City.cs#L11-L21
https://github.com/Neamiades/CoinsDiffusion/blob/90c1fe39fb8ce5285ed7144c0c35efc09d306243/CoinsDiffusion/Country.cs#L9-L21

**Comment by SerhiiYakhin** [comment]
Done in 9b61d2afb8162d093c97c3c34bcb5f2efabb0b41
