### ISSUE TITLE
Improve code

### ISSUE THREAD

**Issue by Den4yk** [Neamiades/CoinsDiffusion#8]
Make local variable to avoid repeating the instructions at each iteration:

https://github.com/Neamiades/CoinsDiffusion/blob/90c1fe39fb8ce5285ed7144c0c35efc09d306243/CoinsDiffusion/Program.cs#L44

**Comment by SerhiiYakhin** [comment]
Done in 9b61d2afb8162d093c97c3c34bcb5f2efabb0b41
